backend:
- name: test-repo
+ name: github
+ repo: squteronsquter/witalneinspiracje
media_folder: static/img
public_folder: /img
collections:
- name: 'blog'
label: 'Blog'
folder: 'content/blog'
slug: 'index'
path: '{{title}}/index'
editor:
  preview: false
fields:
  - { name: path, label: Path }
  - { name: date, label: PublishDate, widget: datetime }
  - { name: title, label: Title }
  - { name: description, label: Description, widget: string }
  - { name: body, label: Body, widget: markdown }
